
import Link from "next/link";
import "./globals.css";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body>
        
        <div className="navbar">
          <img src="/next.svg" width="100" height="20"/>
          <Link href="/business/manage">사업자관리 </Link>
          <Link href="/admin/manage">관리자</Link>
        </div>
       
       {children}

       
      </body>
    </html>
  );
}


export const metadata = {
  title: "쿠폰 관리 - dev ",
  description: "Generated by 포테이토",
  
  icons: {
    icon: "/favicon.png", // 이것만으로는 때때로 불완전할 수 있음
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};